import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Montserrat,
  Birthstone,
  Poppins,
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-montserrat",
  display: "swap",
});
const birthstone = Birthstone({
  subsets: ["latin"],
  weight: "400", // Wajib ditambahkan karena Birthstone bukan variable font
  variable: "--font-birthstone",
  display: "swap",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700", "900"], // Wajib ditambahkan karena Poppins bukan variable font
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${birthstone.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
